version: 2.1
orbs:
  node: circleci/node@1.1.6

jobs:
  intergration_tests:
    docker:
      - image: circleci/node:12.16.1
      - image: neo4j:latest
        entrypoint: /bin/bash
        command: -c "/sbin/tini -g -s -v -- /docker-entrypoint.sh neo4j"
        environment:
          NEO4J_AUTH: neo4j/test
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: install
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: ~/repo
          paths: .
      - run:
          name: Run tests
          command: npx cross-env NEO_USER=neo4j NEO_PASSWORD=test NEO_URL=bolt://localhost:7687/neo4j NEO_WAIT=30000 npm run test-integration

workflows:
  version: 2
  intergration:
    jobs:
      - intergration_tests:
          filters:
            branches:
              only: /master/
