version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  neo4j:
    docker:
      - image: neo4j:latest
    working_directory: ~/repo
    steps:
      - setup_remote_docker
      - run:
          name: Start Neo4j
          command: docker run --detach --name testneo4j -e NEO4J_AUTH='neo4j/test' --publish 7687:7687 -v $HOME/neo4j/data:/data -v $HOME/neo4j/logs:/logs -v $HOME/neo4j/import:/var/lib/neo4j/import -v $HOME/neo4j/plugins:/plugins neo4j:latest

  run_tests:
    docker:
      - image: circleci/node:12.16.1
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Run tests
          command: npx cross-env NEO_USER=neo4j NEO_PASSWORD=test NEO_URL=bolt://localhost:7687/neo4j NEO_WAIT=30000 npm run test-integration

  install_dependencies:
    docker:
      - image: circleci/node:12.16.1
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: install
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: ~/repo
          paths: .

workflows:
  version: 2
  intergration_tests:
    jobs:
      - neo4j:
          filters:
            branches:
              only: /master/
      - install_dependencies:
          filters:
            branches:
              only: /master/
      - run_tests:
          requires:
            - install_dependencies
            - neo4j
          filters:
            branches:
              only: /master/
